name: My Pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Pipeline started"
